export const calcUI = [
  { button: "AC", id: "clear" },
  { button: "/", id: "divide" },
  { button: "x", id: "multiply" },
  { button: "7", id: "seven" },
  { button: "8", id: "eight" },
  { button: "9", id: "nine" },
  { button: "-", id: "substract" },
  { button: "4", id: "four" },
  { button: "5", id: "five" },
  { button: "6", id: "six" },
  { button: "+", id: "add" },
  { button: "1", id: "one" },
  { button: "2", id: "two" },
  { button: "3", id: "three" },
  { button: "=", id: "equals" },
  { button: "0", id: "zero" },
  { button: ".", id: "decimal" },
];
